
import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, CheckCircle, Cpu, Layers, RefreshCw, Settings, User, Phone, Mail, Zap, Monitor, Speaker, Sun, Box, Gamepad2, Grid } from 'lucide-react';
import SEO from '../components/SEO';
import ServiceSidebar from '../components/ServiceSidebar';
import { useScrollAnimation } from '../lib/useScrollAnimation';

const DATA = {
  title: 'Design & Development (R&D)',
  subtitle: 'Innovation, Indigenization & Technology Transfer',
  image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&q=80",
  description: `
    <p class="lead text-lg text-gray-700 dark:text-gray-300 mb-6">
      Design and Development is a continuous activity at the Institute and it is purely based on the emerging needs of the instrument industry. The main objective behind the Institute’s design and development work is to transfer the technical know-how developed to the instrument manufacturers or entrepreneurs on nonexclusive basis.
    </p>
    <p class="text-gray-600 dark:text-gray-400 mb-6">
      The Small Scale units, by and large, are not in a “position” to bear R&D expenditure and moreover quite often they are not aware of the latest development trends. The development work at the IDEMI’s laboratory has, therefore, attracted many units and entrepreneurs and has resulted in a good rapport between the Institute and various manufacturing units.
    </p>
    <p class="text-gray-600 dark:text-gray-400">
      The department normally undertakes the development work in consultation with the users as well as the manufacturers so that the right type of product is developed which is commercially viable. Institute’s achievements in the design and development field and details on prototypes developed are published through displays at exhibitions apart from individual contacts/communications. Entrepreneurs and Manufacturers are always approaching the Institute for any design and development assistance that may be required by them from time to time.
    </p>
  `,
  projects: [
    { 
        title: 'Telepresence Robot', 
        image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&q=80",
        desc: 'This is a very effective product in COVID-19 situation, to avoid direct contact of doctor and patient. This robot has a laptop upside to communicate with Doctor. The embedded microcontroller board installed at the bottom of robot guides it during locomotion. Its unique shape and attractive design makes it is easy to spot it from far distance and avoid possible collision with individuals. The material used is kept light weight to optimise the battery usage.',
        applications: ['Video-conferencing', 'Telemedicine', 'Medical Applications'],
        icon: <Monitor size={24} />
    },
    { 
        title: 'Solar Silk Reeling & Spinning Machine', 
        image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&q=80",
        desc: 'This product works on solar energy. The target group of people for this product are Rural / Women Entrepreneur. It can operate & extract Silk Thread from Cocoons with the help of Machine. Very tidy design approach is followed. Low power DC motors look after spinning and collection of Silk from cocoons. The idea of collecting the silk from cocoons is one of its kinds. Massive implementation of this machine will lower the time required for silk extraction.',
        icon: <Sun size={24} />
    },
    { 
        title: 'Solar Trash Compactor', 
        image: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&q=80",
        desc: 'This product is intended for innovative way of waste management. Solar-Powered Trash Compactor helps keeping public spaces clean and can reduce trash collection frequency. The embedded system installed inside the compactor is battery operated. Battery gets all its charge from the electricity generated by solar panel. The embedded system automatically senses the quantity of trash collected and compresses it to raise the capacity of bin upto three times.',
        icon: <Box size={24} />
    },
    { 
        title: 'Peg Mirror', 
        image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80",
        desc: 'This project was developed for NSCM. The project has more than one thousand servo motors connected with wooden pegs on their end. The end of all wooden pegs is cut for certain angle. By turning the pegs in clockwise or anti-clockwise direction makes it possible to create an image. A camera posing in front takes HD image of the subject. The image has certain pixel resolution which determines the final position of pegs to project its image.',
        icon: <Grid size={24} />
    },
    { 
        title: 'Leap Ball Maze', 
        image: "https://images.unsplash.com/photo-1614632537190-23e4146777db?auto=format&fit=crop&q=80",
        desc: 'Developed for NSCM, this project is a major attraction from all age groups. It can be seen as an enlarged version of a hand-held maze game. To put the ball at the center of the maze, one needs to position operators hand over the sensor, which converts the motion into the input for embedded system. The embedded system takes the inputs from sensors and controls the mechanical movements through actuators.',
        icon: <Gamepad2 size={24} />
    },
    { 
        title: 'Rubik Cube Solver', 
        image: "https://images.unsplash.com/photo-1591991564021-0662a8573199?auto=format&fit=crop&q=80",
        desc: 'Developed for NSCM. Rubik’s cube; a toy that has its unique color patterns & tricky part is where one needs to position single colour on every face. This project uses the faster computational abilities of embedded systems and gives optimal solution. It is one of the eye-catching projects developed by the embedded system team.',
        icon: <Cpu size={24} />
    },
    { 
        title: 'Robotic Air Hockey', 
        image: "https://images.unsplash.com/photo-1535378437327-664c821d1711?auto=format&fit=crop&q=80",
        desc: 'Developed for NSCM. The conventional hockey table has two players whereas in robotic air-hockey, it is machine v/s human. The key focus of the player is to put the puck inside goal post by defeating the machine. It uses advanced sensors and actuators for real-time response.',
        icon: <Settings size={24} />
    },
    { 
        title: 'Public Addressing System', 
        image: "https://images.unsplash.com/photo-1520697779741-9da0605a96db?auto=format&fit=crop&q=80",
        desc: 'A public address system (PAS) is a wireless electronic system comprising amplifiers, loudspeakers, and related equipment. It increases the apparent volume (loudness) of a human voice. Very useful in COVID-19 for emergency announcements in local areas, schools, colleges, and crowded places.',
        features: ['Plug and play device', 'Wireless connectivity', 'No distance barrier', '30 mins reserve battery'],
        icon: <Speaker size={24} />
    },
    { 
        title: 'Automatic Hand Sanitizer Dispenser', 
        image: "https://images.unsplash.com/photo-1584634731339-252c581abfc5?auto=format&fit=crop&q=80",
        desc: 'This product has a unique feature of dispensing liquid sanitizer without making actual contact with the equipment. It uses IR sensors to detect hands and release a sufficient quantity of sanitizer. It is designed to prevent continuous dispensing if hands are kept below the sensor.',
        features: ['220 x 140 x 75 mm Dimensions', '1 Ltr Capacity', '5V/1A Adaptor', 'Easy to refill'],
        icon: <CheckCircle size={24} />
    }
  ],
  capabilities: [
    {
        title: 'Product Innovation',
        desc: 'Conceptualizing and designing new products from scratch, focusing on aesthetics, ergonomics, and functionality.',
        icon: <Settings size={24} className="text-secondary" />
    },
    {
        title: 'Reverse Engineering',
        desc: 'Generating 3D CAD models and manufacturing drawings from physical parts using high-precision 3D Scanners and CMMs.',
        icon: <RefreshCw size={24} className="text-secondary" />
    },
    {
        title: 'Import Substitution',
        desc: 'Developing cost-effective, indigenous alternatives for expensive imported assemblies without compromising on quality.',
        icon: <Layers size={24} className="text-secondary" />
    },
    {
        title: 'Electronics Design',
        desc: 'PCB Design, Firmware development, and embedded system design for industrial automation and control applications.',
        icon: <Cpu size={24} className="text-secondary" />
    }
  ],
  specializedServices: [
    {
        title: 'SMT Assembly',
        desc: 'Surface Mount Technology (SMT) assembly services for prototypes and low-to-medium volume production.',
        link: '/services/design-development/smt-assembly'
    },
    {
        title: 'Technology Transfer',
        desc: 'Commercialization of indigenous technologies developed by IDEMI R&D for mass manufacturing.',
        link: '/services/design-development/techtransfer'
    }
  ],
  contact: {
    name: 'Mr. Shripankh Patil',
    designation: 'Assistant Director',
    email: 'dnd@idemi.org',
    altEmails: ['automation@idemi.org', 'embedded@idemi.org'],
    phone: '022-24050301/02/03/04 ext 291/293/294/238',
    mobile: '8652892469'
  }
};

const DesignDevelopment: React.FC = () => {
  useScrollAnimation();
  return (
    <div className="bg-gray-50 dark:bg-gray-950 min-h-screen transition-colors duration-200">
      <SEO 
        seo={{ 
          title: 'Design & Development Services - R&D, Import Substitution & Reverse Engineering | IDEMI', 
          description: 'Innovation-driven Design & Development services for Import Substitution, Reverse Engineering, and Indigenization of critical components for Defence and Aerospace sectors. Supporting Startups and MSMEs.',
          keywords: ['Design & Development', 'R&D Services', 'Import Substitution', 'Reverse Engineering', 'Product Design', 'Indigenization', 'Defence', 'Aerospace', 'Innovation'],
          schemaType: 'Service'
        }} 
        path="/services/design-development" 
      />
      
      <div className="bg-white dark:bg-gray-900 border-b border-gray-200 dark:border-gray-800">
        <div className="container mx-auto px-4 py-4">
             <Link to="/services" className="inline-flex items-center text-sm text-gray-500 hover:text-primary transition-colors mb-2">
                <ArrowLeft size={16} className="mr-1" /> Back to Services
             </Link>
             <h1 className="text-3xl font-bold text-gray-900 dark:text-white">{DATA.title}</h1>
        </div>
      </div>

      <div className="container mx-auto px-4 py-12 flex flex-col lg:flex-row gap-12">
          <aside className="lg:w-1/4">
             <ServiceSidebar />
          </aside>

          <div className="lg:w-3/4">
             <div className="bg-white dark:bg-gray-800 p-8 rounded-xl shadow-sm border border-gray-100 dark:border-gray-700 reveal-on-scroll">
                <p className="text-primary dark:text-blue-400 font-bold uppercase tracking-wide text-sm mb-4">{DATA.subtitle}</p>
                
                <img src={DATA.image} alt={DATA.title} className="w-full h-64 md:h-96 object-cover rounded-lg mb-8 shadow-md" />

                <div 
                    className="prose prose-lg dark:prose-invert max-w-none mb-12"
                    dangerouslySetInnerHTML={{ __html: DATA.description }}
                />

                <div className="grid md:grid-cols-2 gap-8 mb-16">
                    {DATA.capabilities.map((cap, idx) => (
                        <div key={idx} className="flex gap-4">
                            <div className="shrink-0 mt-1 bg-gray-50 dark:bg-gray-700/50 p-3 rounded-lg h-fit">
                                {cap.icon}
                            </div>
                            <div>
                                <h3 className="font-bold text-gray-900 dark:text-white mb-2">{cap.title}</h3>
                                <p className="text-sm text-gray-600 dark:text-gray-300 leading-relaxed">{cap.desc}</p>
                            </div>
                        </div>
                    ))}
                </div>

                {/* Innovative R&D Projects */}
                <div className="mb-16">
                    <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-8 border-l-4 border-secondary pl-4 flex items-center gap-2">
                        <Zap size={20} className="text-secondary" /> Featured R&D Projects
                    </h3>
                    <div className="grid grid-cols-1 gap-12">
                        {DATA.projects.map((project, idx) => (
                            <div key={idx} className="flex flex-col md:flex-row gap-6 bg-gray-50 dark:bg-gray-700/20 p-6 rounded-2xl border border-gray-100 dark:border-gray-700 hover:shadow-lg transition">
                                <div className="md:w-1/3 shrink-0">
                                    <div className="aspect-[4/3] rounded-xl overflow-hidden shadow-sm bg-white dark:bg-gray-800">
                                        <img 
                                            src={project.image} 
                                            alt={project.title} 
                                            className="w-full h-full object-cover transform hover:scale-105 transition duration-500"
                                            loading="lazy"
                                        />
                                    </div>
                                </div>
                                <div className="md:w-2/3">
                                    <div className="flex items-center gap-3 mb-3">
                                        <div className="p-2 bg-white dark:bg-gray-800 rounded-lg text-primary dark:text-blue-400 shadow-sm">
                                            {project.icon}
                                        </div>
                                        <h4 className="font-bold text-xl text-gray-900 dark:text-white">{project.title}</h4>
                                    </div>
                                    <p className="text-gray-600 dark:text-gray-300 text-sm leading-relaxed mb-4">{project.desc}</p>
                                    
                                    {project.applications && (
                                        <div className="mb-4">
                                            <p className="text-xs font-bold text-gray-500 dark:text-gray-400 uppercase mb-2">Applications</p>
                                            <div className="flex flex-wrap gap-2">
                                                {project.applications.map((app, aIdx) => (
                                                    <span key={aIdx} className="px-2 py-1 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-600 rounded text-xs text-gray-700 dark:text-gray-300">{app}</span>
                                                ))}
                                            </div>
                                        </div>
                                    )}

                                    {project.features && (
                                        <div>
                                            <p className="text-xs font-bold text-gray-500 dark:text-gray-400 uppercase mb-2">Key Features</p>
                                            <ul className="grid grid-cols-1 sm:grid-cols-2 gap-1 text-sm text-gray-600 dark:text-gray-300">
                                                {project.features.map((feat, fIdx) => (
                                                    <li key={fIdx} className="flex items-center gap-2">
                                                        <CheckCircle size={12} className="text-green-500" /> {feat}
                                                    </li>
                                                ))}
                                            </ul>
                                        </div>
                                    )}
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

                {/* Specialized Units */}
                <div className="mb-12">
                    <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-6 border-l-4 border-primary pl-4">Specialized Units</h3>
                    <div className="grid md:grid-cols-2 gap-6">
                        {DATA.specializedServices.map((service, idx) => (
                            <div key={idx} className="bg-gray-50 dark:bg-gray-700/30 p-6 rounded-lg border border-gray-100 dark:border-gray-700 hover:shadow-md transition flex flex-col">
                                <h4 className="font-bold text-lg text-primary dark:text-blue-400 mb-2">{service.title}</h4>
                                <p className="text-sm text-gray-600 dark:text-gray-300 mb-4 flex-grow">{service.desc}</p>
                                <Link to={service.link} className="text-xs font-bold uppercase tracking-wider text-secondary flex items-center gap-1 hover:underline self-start">
                                    Learn More <ArrowLeft size={12} className="rotate-180" />
                                </Link>
                            </div>
                        ))}
                    </div>
                </div>

                {/* Contact Card */}
                <div className="bg-gradient-to-br from-blue-50 to-white dark:from-gray-800 dark:to-gray-900 p-8 rounded-2xl border border-blue-100 dark:border-gray-700 shadow-sm">
                    <div className="flex flex-col md:flex-row gap-8 items-start md:items-center">
                        <div className="p-4 bg-primary text-white rounded-full shadow-lg shrink-0">
                            <User size={32} />
                        </div>
                        <div className="flex-grow space-y-1">
                            <h3 className="text-xs font-bold text-secondary uppercase tracking-widest mb-1">Contact Person</h3>
                            <p className="font-bold text-gray-900 dark:text-white text-2xl">{DATA.contact.name}</p>
                            <p className="text-sm font-medium text-gray-500 dark:text-gray-400 mb-4">{DATA.contact.designation}</p>
                            
                            <div className="flex flex-col sm:flex-row gap-y-2 gap-x-8 text-sm text-gray-700 dark:text-gray-300 pt-2 border-t border-gray-200 dark:border-gray-700">
                                <a href={`mailto:${DATA.contact.email}`} className="flex items-center gap-2 hover:text-primary dark:hover:text-blue-400 transition group">
                                    <Mail size={16} className="text-gray-400 group-hover:text-primary dark:group-hover:text-blue-400" /> {DATA.contact.email}
                                </a>
                                {DATA.contact.altEmails.map((email, i) => (
                                    <a key={i} href={`mailto:${email}`} className="flex items-center gap-2 hover:text-primary dark:hover:text-blue-400 transition group">
                                        <Mail size={16} className="text-gray-400 group-hover:text-primary dark:group-hover:text-blue-400" /> {email}
                                    </a>
                                ))}
                                <div className="flex items-center gap-2">
                                    <Phone size={16} className="text-gray-400" /> 
                                    <span>{DATA.contact.phone}</span>
                                </div>
                                <div className="flex items-center gap-2">
                                    <Phone size={16} className="text-gray-400" /> 
                                    <span>+91 {DATA.contact.mobile}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

             </div>
          </div>
      </div>
    </div>
  );
};

export default DesignDevelopment;
