
import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, CheckCircle, Sun, Zap, Recycle, Settings, ArrowRight, User, Mail, Phone } from 'lucide-react';
import SEO from '../components/SEO';
import ServiceSidebar from '../components/ServiceSidebar';
import { useScrollAnimation } from '../lib/useScrollAnimation';

const PRODUCTS = [
  {
    title: "Plasma Activated Ozone Sanitiser",
    description: "Plasma Activated Ozone Sanitizer is developed for hand sanitization by application of Ozone gas. In comparison with other methods of hand sanitization like soaps or chemicals, this method does not affect the human skin rather it only targets bacteria and also does not leave its trace on palms. Also it does not require periodic refill as it uses electricity for the operation. Just by using electricity, Ozone gas is generated by the equipment.",
    image: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&q=80",
    features: [
        "Works on single phase 230 V supply",
        "Generates 10ppm ozone gas as output",
        "Controls exposure ensuring safe operation",
        "Compact size for house, offices and public places"
    ],
    status: "This technology is transferred to National Research Development Corporation (NRDC), New Delhi.",
    icon: <Zap className="text-blue-500" size={24} />
  },
  {
    title: "Solar Operated Trash Compactor",
    description: "The Purpose Behind designing this machine was to reduce the waste by Volume by Compacting the dry trash. The compactor is a smart Garbage bin which helps to compress the trash, hence reducing the trash which comes out of the Garbage bins situated on road. It works on low running cost since it is solar Operated.",
    image: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&q=80",
    features: [
        "Capacity is 5 times that of normal Trash Can",
        "Works totally on solar energy",
        "SMS indication to Cleaning staff when full",
        "Suitable for Gardens, Public places, Bus stands, Railway Station"
    ],
    icon: <Sun className="text-amber-500" size={24} />
  },
  {
    title: "Rapid Composting Machine",
    description: "This machine is an ultimate solution to the worsening waste disposal and Natural Resources management problem. With our Rapid Composition Digestion Technology it converts organic waste into organic fertilizer by using our specially designed Rapid Composting Machine and Digestion Reactor and Additive solution which turn the Waste into Wealth. The end product is high-nutrient organic fertilizer that improves soil water holding and exchange capacity.",
    image: "https://images.unsplash.com/photo-1589923188900-85dae5233271?auto=format&fit=crop&q=80",
    features: [
        "Model: Rapid Composting Machine",
        "Operation Capacity: 80 kg/shift (8hrs./day)",
        "Power Supply: 3-Phase / 220 Volts AC",
        "Reduces inorganic fertilizer consumption"
    ],
    icon: <Recycle className="text-green-600" size={24} />
  }
];

const CONTACT = {
    name: "Mr. Shripankh Patil",
    designation: "Assistant Director",
    email: "dnd@idemi.org",
    phone: "022-24050301 ext 238",
    mobile: "8652892469"
};

const TechTransfer: React.FC = () => {
  useScrollAnimation();
  return (
    <div className="bg-gray-50 dark:bg-gray-950 min-h-screen transition-colors duration-200">
      <SEO 
        seo={{ 
          title: 'Technology Transfer | IDEMI', 
          description: 'Products available for Technology Transfer: Plasma Ozone Sanitiser, Solar Trash Compactor, and Rapid Composting Machine.',
          keywords: ['technology transfer', 'indigenous technology', 'ozone sanitiser', 'solar trash compactor', 'rapid composting machine', 'waste to wealth', 'NRDC'],
          schemaType: 'Service'
        }} 
        path="/services/design-development/techtransfer" 
      />
      
      <div className="bg-white dark:bg-gray-900 border-b border-gray-200 dark:border-gray-800">
        <div className="container mx-auto px-4 py-4">
             <Link to="/services/design-development" className="inline-flex items-center text-sm text-gray-500 hover:text-primary transition-colors mb-2">
                <ArrowLeft size={16} className="mr-1" /> Back to Design Services
             </Link>
             <h1 className="text-3xl font-bold text-gray-900 dark:text-white">Technology Transfer</h1>
        </div>
      </div>

      <div className="container mx-auto px-4 py-12 flex flex-col lg:flex-row gap-12">
          <aside className="lg:w-1/4">
             <ServiceSidebar />
          </aside>

          <div className="lg:w-3/4">
             <div className="bg-white dark:bg-gray-800 p-8 rounded-xl shadow-sm border border-gray-100 dark:border-gray-700 reveal-on-scroll">
                <p className="text-primary dark:text-blue-400 font-bold uppercase tracking-wide text-sm mb-4">Products for Technology Transfer</p>
                <img src="https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80" alt="Tech Transfer" className="w-full h-64 md:h-96 object-cover rounded-lg mb-8 shadow-md" />
                
                <p className="text-lg text-gray-700 dark:text-gray-300 mb-12">
                    IDEMI develops indigenous technologies and products through its R&D cell and offers them to MSMEs for commercial manufacturing. Below are the key products currently available for technology transfer.
                </p>

                <div className="space-y-12">
                    {PRODUCTS.map((product, idx) => (
                        <div key={idx} className="flex flex-col md:flex-row gap-8 bg-gray-50 dark:bg-gray-700/20 p-6 rounded-2xl border border-gray-100 dark:border-gray-700 hover:shadow-lg transition duration-300">
                            <div className="md:w-1/3 shrink-0">
                                <div className="rounded-xl overflow-hidden h-48 bg-white dark:bg-gray-800 shadow-sm relative group">
                                    <img 
                                        src={product.image} 
                                        alt={product.title} 
                                        className="w-full h-full object-cover transform group-hover:scale-105 transition duration-500" 
                                    />
                                    <div className="absolute top-3 right-3 bg-white dark:bg-gray-800 p-2 rounded-full shadow-md">
                                        {product.icon}
                                    </div>
                                </div>
                            </div>
                            <div className="md:w-2/3 flex flex-col">
                                <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-3">{product.title}</h3>
                                <p className="text-sm text-gray-600 dark:text-gray-300 mb-6 leading-relaxed flex-grow">
                                    {product.description}
                                </p>
                                
                                <div className="bg-white dark:bg-gray-800 rounded-lg p-4 mb-4 border border-gray-100 dark:border-gray-600">
                                    <h4 className="text-xs font-bold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-3 flex items-center gap-2">
                                        <Settings size={14} /> Key Features / Specs
                                    </h4>
                                    <ul className="grid sm:grid-cols-2 gap-2">
                                        {product.features.map((feature, fIdx) => (
                                            <li key={fIdx} className="flex items-start gap-2 text-xs text-gray-700 dark:text-gray-300">
                                                <CheckCircle size={14} className="text-secondary shrink-0 mt-0.5" />
                                                <span>{feature}</span>
                                            </li>
                                        ))}
                                    </ul>
                                </div>

                                {product.status && (
                                    <div className="text-xs font-semibold text-green-700 dark:text-green-400 bg-green-50 dark:bg-green-900/20 px-3 py-2 rounded-lg border border-green-100 dark:border-green-800">
                                        Note: {product.status}
                                    </div>
                                )}
                            </div>
                        </div>
                    ))}
                </div>
                
                {/* Contact Card */}
                <div className="mt-12 bg-blue-50 dark:bg-gray-800 p-6 rounded-xl border border-blue-100 dark:border-gray-700 h-fit">
                    <h3 className="text-lg font-bold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
                        <User className="text-primary dark:text-blue-400" size={20} /> Contact Person
                    </h3>
                    <div className="space-y-1">
                        <p className="font-bold text-gray-900 dark:text-white text-lg">{CONTACT.name}</p>
                        <p className="text-xs font-bold text-secondary dark:text-amber-500 uppercase tracking-wider mb-3">{CONTACT.designation}</p>
                        
                        <div className="space-y-2 text-sm text-gray-700 dark:text-gray-300 pt-2 border-t border-blue-200 dark:border-gray-600">
                            <a href={`mailto:${CONTACT.email}`} className="flex items-center gap-2 hover:text-primary dark:hover:text-blue-400 transition group">
                                <Mail size={16} className="text-gray-400 group-hover:text-primary dark:group-hover:text-blue-400" /> {CONTACT.email}
                            </a>
                            <div className="flex items-center gap-2">
                                <Phone size={16} className="text-gray-400" /> 
                                <span>{CONTACT.phone}</span>
                            </div>
                            <div className="flex items-center gap-2">
                                <Phone size={16} className="text-gray-400" /> 
                                <span>+91 {CONTACT.mobile}</span>
                            </div>
                        </div>
                    </div>
                </div>

             </div>
          </div>
      </div>
    </div>
  );
};

export default TechTransfer;
